a.out: main.cxx session.cxx protocol.cxx headers/session.H headers/protocol.H headers/comm.H
	g++ main.cxx session.cxx protocol.cxx -I/usr/include/GameNetworkingSockets /usr/lib/x86_64-linux-gnu/libGameNetworkingSockets.so -Wall -Wextra -Wpedantic 
	echo "done."
